# Generated by Django 3.1.8 on 2023-04-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230408_1128'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('EOD_figure', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tranx_date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eod_records', to='accounts.userbankaccount')),
            ],
            options={
                'ordering': ['tranx_date'],
            },
        ),
    ]
