# Generated by Django 3.1.8 on 2023-04-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_eod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eod',
            name='amount',
        ),
    ]
